UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/LSnv3vTS8k8sG1hk8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Todos unidos' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/VwzVpNkNAT1v6VeAA', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '28 de Diciembre' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/z9JBuSf67rpfKUPt6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Amar y vivir' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/uPA9QWdKh6Hjxq6y6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Amor y gratitud' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/CCjwmbeMYwZgKdV67', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Progreso' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/AH6mT9Zc5rX9apjG6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '3 de septiembre' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/sRmhzjrcnanjcCh19', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Akron' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/EZCjQzJqhqH7qEdR8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Amigo' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/9dDXbaPCgR48TNsU8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Plenitud' AND distrito = '1';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/bPnq4BQyNFTq8eLA9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '13 de Enero' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/eBLCsNa7keN4Uqk16', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Un nuevo amanecer' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/LsVCcd8php5PFY9c7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'En acción' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/CBvxaq79LD7aUkaN9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Paz y vida' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/bGF9nZCUEc6MZhpv7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Una mano para ti' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/xKbvy8WrKB1WWxhv6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'El Mar' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/Z6QHkyva6PSWSt2Q7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Paso doce' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/fLnyc9zJjzfbDS5K9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Renacimiento' AND distrito = '2';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/Jy3DbadLEswvFDuB7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Cachanilla' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/sCwucjUdAiif2Xxp7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Doce y doce' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/dqFLTBqXyAae73mu5', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Los Pinos' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/SkMbfaedoDA936Cv8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Pioneros' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/DKckZ1rNcmFto6Xu5', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'San Pedro' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/5btDWDFdxSNUzixTA', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '24 de Enero' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/Z2osEDBsqtMRSuh8A', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Despertar espiritual' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/NtuQSJcJqCRXPZtQ8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Independencia 24' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/RyRHCJiHeg6cucZB9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Renacimiento' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/wxzuTFqCD6zHqW3N7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Vive y deja vivir' AND distrito = '3';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/UAdu4gJrMqQMRuiE7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Mi nuevo camino' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/ApSHpL3BrNdye39H7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Puerto Seguro' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/g535ktS8avo3iB3P8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Un día a la vez' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/cw57HfH9r31P5Cdd9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Unidad' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/YLiuz5qTuThQ5WF49', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Vivir mejor "El rescate"' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/sjPPrxYs7Xqk2pkx8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '12 promesas' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/3EA51xD6WKntZqbt9', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Hidalgo' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/YAQZAqH9AdAdECc59', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Primero de Enero' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/2UD8p6HogdSn1hXL6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Transmítelo' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/H1ChgqSq4HVTq6ut7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Una nueva vida' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/dbjsZjENYLu5Gi4Z7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Cucapah' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/RBD6QPKP6rw3MMuC7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Andando sobrio' AND distrito = '4';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/kR2koZjhHdDrk9d17', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'South Campos Serenity Group' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/bVVnBXCWB5NeJ2Wt6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Internacional' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/wRzMbKig2Wxu8wCn7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'San Felipe' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/JeSsuhQUEmAdbpiq7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Living Sober' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/nqytFVFEFBzc7yV29', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '17 de Octubre' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/nnrF9JMfv8VbNDXc6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Renacer' AND distrito = '5';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/KJEJw7q7KFntnv1M6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '21 de julio' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/6jeowbfFiHVKaMuz7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Fortaleza' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/qYL3TP66KXk3zeDV8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Hoy es diferente' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/3zJT4iw4vB1QcFJ37', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Libertad' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/ozyz1GFQcoRzF4co8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Una visión para ti' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/KfwgnKiJ6X2tJLTX6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Bill y Bob' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/XJ8E3kGmLmFErLiQ7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Experiencia espiritual' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/4NCTc9A68LFHst5A8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Gratitud' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/TdXXzvNGkJg5rPC47', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Humildad' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/dEsiuNtvS7WNsntK7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Pedregal' AND distrito = '6';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/mYJGBbpbCXe7tXjcA', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Firme voluntad' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/H3aXDtqhMmCCeUx1A', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Alto' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/Y3YdDx5ZHpwV1GsC6', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Oaxaca' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/s91Srfq4vLVKYKhcA', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Cambio de conciencia' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/fav5mqE3BfRL66Yw7', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Una nueva visión' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/firDx9nt97wcnGu4A', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = '2 de abril' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/1Cnr1HuSzRzWTffCA', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Una esperanza de fe' AND distrito = '7';
UPDATE grupos SET maps_url = 'https://maps.app.goo.gl/FgyT1iVBqoCuCqqi8', lat = NULL, lng = NULL, precision_ubic = NULL, geo_intento = 0 WHERE grupo = 'Anahuac' AND distrito = '7';
