-- Carga inicial de grupos desde el Excel del área.
-- OJO: borra la tabla anterior (incluye los grupos de prueba) y la vuelve a crear.
-- Tabla de grupos: alimenta el Directorio y el Mapa.
DROP TABLE IF EXISTS grupos;
CREATE TABLE grupos (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  distrito    TEXT    NOT NULL,
  grupo       TEXT    NOT NULL,
  ciudad      TEXT    NOT NULL,
  estado      TEXT,
  direccion   TEXT,
  colonia     TEXT,
  cp          TEXT,
  referencia  TEXT,
  terapia     TEXT,
  personas    TEXT,
  idioma      TEXT,
  horario     TEXT,
  telefono    TEXT,
  lat         REAL,
  lng         REAL,
  maps_url    TEXT,
  precision_ubic TEXT,
  geo_intento INTEGER NOT NULL DEFAULT 0,
  activo      INTEGER NOT NULL DEFAULT 1,
  actualizado TEXT    NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_grupos_activo ON grupos (activo);

INSERT INTO grupos (distrito, grupo, ciudad, estado, direccion, colonia, cp, referencia, terapia, personas, idioma, horario, telefono, maps_url) VALUES
('1', 'Todos unidos', 'Mexicali', 'Baja California', 'Carretera Santa Isabel km 2.5', 'Villas del Real', '21309', 'A lado de una tienda "Six"', 'Tradicional', 'Mixto', 'Español', 'Diario de 3:00 a 5:00 pm.', NULL, NULL),
('1', '28 de Diciembre', 'Mexicali', 'Baja California', 'Paseo de San Marcos #104-10', 'San Marcos', '21050', 'Frente a la glorieta La Luna', 'Tradicional', 'Mixto', 'Español', 'Lunes a domingo de 7:00 a 8:30 pm.', NULL, NULL),
('1', 'Amar y vivir', 'Mexicali', 'Baja California', 'Av. Michoacán #2349', 'Revolución', '21110', 'esquina con Bahia Magdalena', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm (invierno) y 8:00 a 9:30 pm (verano)', NULL, NULL),
('1', 'Amor y gratitud', 'Mexicali', 'Baja California', 'Calle Santa Ana #3579', 'Mayos', '21137', 'A tres cuadras del campo de beisbol', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm.', NULL, NULL),
('1', 'Progreso', 'Mexicali', 'Baja California', 'Abelardo L. Rodriguez #201-1', 'Progreso', '21188', 'esquina calle Nuevo León', 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 8:00 a 9:30 pm.', NULL, NULL),
('1', '3 de septiembre', 'Mexicali', 'Baja California', 'Av. Michoacan y calle tercera', 'Pueblo Nuevo', '21120', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 3:00 a 5:00 pm', NULL, NULL),
('1', 'Akron', 'Mexicali', 'Baja California', 'Blvd. Lázaro Cárdenas #1670-1', 'Villafontana', '21180', 'Entre Refaccionaria MR y Laboratorios Simi', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm.', NULL, NULL),
('1', 'Amigo', 'Mexicali', 'Baja California', 'Av. Yugoslavia #2814, local 3', 'Popular Nacionalistas', '21165', 'esquina con calle Ingenieros', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm.', NULL, NULL),
('1', 'Plenitud', 'Mexicali', 'Baja California', 'Av. Luis Echeverria #1189', 'Orizaba', '21160', 'Conjunto Urbano Orizaba', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm.', NULL, NULL),
('2', '13 de Enero', 'Mexicali', 'Baja California', 'Av. Juan Aldama #300', 'Ciudad Morelos (Cuervos)', '21960', 'Juan Aldama', 'Tradicional', 'Mixto', 'Español', 'Diario de 6:00 a 7:30 pm (invierno) y 7:00 a 8:30 pm (verano)', '686 311 45 88', NULL),
('2', 'Un nuevo amanecer', 'Mexicali', 'Baja California', 'Av. B #599 L-4 entre calles 6 Y 7', 'Vicente Guerrero (Algodones)', '21970', 'esquina con abarrotes Valle los Algodones', 'Tradicional', 'Mixto', 'Español', 'Lunes a jueves de 7:00 a 8:30 pm (invierno) y 8:00 a 9:30 pm (verano)', '686 578 0345', NULL),
('2', 'En acción', 'San Luis Río Colorado', 'Sonora', 'Av. Libertad y Calle 20', 'Residencias', '83448', 'A un costado de la estetica', 'Tradicional', 'Mixto', 'Español', 'Diario de 1:00 a 2:30 pm y de 7:00 a 8:30 pm.', '653 177 69 35 / 653 136 20 66', NULL),
('2', 'Paz y vida', 'San Luis Río Colorado', 'Sonora', 'Av. Kino #3107', 'Burócrata', '83450', 'entre calles 31 y 32 San Luis Rio Colorado Sonora', 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:00 a 8:30 pm. Y domingo de 1:00 a 2:30 pm', NULL, NULL),
('2', 'Una mano para ti', 'San Luis Río Colorado', 'Sonora', 'calle 17 #1608 y avenida Puebla', 'Federal', '83489', 'entre Av. Coahuila B y av. Puebla', 'Tradicional', 'Mixto', 'Español', 'Diario 7:30 a 9:00 pm.', NULL, 'https://maps.app.goo.gl/DW8y9PqDVpX1c9hRA?g_st=ac'),
('2', 'El Mar', 'San Luis Río Colorado', 'Sonora', 'Av. Tlaxcala y Pesqueira', 'Ruiz Cortines', '83439', 'esquina con calle pesqueira', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm (invierno) y 8:00 a 9:30 pm (verano)', '653 106 48 02 / 653 111 23 03', NULL),
('2', 'Paso doce', 'San Luis Río Colorado', 'Sonora', 'Av. Revolución 580', 'San Luis Río Colorado Centro', '83400', 'entre calles 5 y 6', 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:00 a 8:30 pm (invierno) y 8:00 a 9:30 pm (verano)', '638 112 05 89 / 653 849 72 36', NULL),
('2', 'Renacimiento', 'San Luis Río Colorado', 'Sonora', 'Madero y Morelos s/n. San Luis Rio Colorado, Sonora', 'Cuauhtémoc', '83400', 'Av. Madero esquina con Morelos', 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:00 a 8:30 pm. Y sábado y domingo de 11:00 am a 12:30 pm.', '653 116 52 91', NULL),
('3', 'Cachanilla', 'Mexicali', 'Baja California', 'Av. Obregón #710 altos', 'Segunda Sección', '21100', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm y domingos de 11:00 am a 12:30 pm.', NULL, NULL),
('3', 'Doce y doce', 'Mexicali', 'Baja California', 'Boulevard Macristy de Hermosillo # 881-12', 'República Mexicana', '21250', '"Plaza Colibrï" altos', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 am y de 8:00 a 9:30 pm.', NULL, NULL),
('3', 'Los Pinos', 'Mexicali', 'Baja California', 'Venustiano Carranza #292 L-8', 'Jardines del Valle', '21270', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 7:00 a 8:30 pm', NULL, NULL),
('3', 'Pioneros', 'Mexicali', 'Baja California', 'Ulises Irigoyen (calle F) #2438-B', 'Libertad', '21030', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 7:30 a 9:00 am; sábado y domingo de 8:00 a 9:30 am', NULL, NULL),
('3', 'San Pedro', 'Mexicali', 'Baja California', 'Calz. de las Americas #999 L-5', 'Cuauhtémoc Norte', '21200', 'Plaza de las Américas', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm', NULL, NULL),
('3', '24 de Enero', 'Mexicali', 'Baja California', 'Calle F y Callejón Tapiceros', 'Industrial', '21010', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 12:00 a 2:00 pm y de 6:00 a 8:00 pm (invierno); 7:00 a 8:30 pm (verano) y lunes, martes, jueves y sábado 7:30 a 9:00 am', NULL, NULL),
('3', 'Despertar espiritual', 'Mexicali', 'Baja California', 'Rio Fuerte 599-2,entre Ignacio Ramirez y Dr. Mora', 'Prohogar', '21240', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:30 a 9:00 pm.', NULL, NULL),
('3', 'Independencia 24', 'Mexicali', 'Baja California', 'Rio Culiacán e Ignacio Comonfort #898-6', 'Prohogar', '21240', 'Altos', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm.', NULL, NULL),
('3', 'Renacimiento', 'Mexicali', 'Baja California', 'Av. Independencia #1944-5', 'Calafia', '21040', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a domingo de 6:30 a 8:00 pm.', NULL, NULL),
('3', 'Vive y deja vivir', 'Mexicali', 'Baja California', 'Rio Elota 1090, altos local 3.', 'Benito Juárez', '21723', NULL, 'Tradicional', 'Mixto', 'Español', 'Todos los días de 7:00 a 8:30 pm.', NULL, NULL),
('4', 'Mi nuevo camino', 'Mexicali', 'Baja California', 'Calz. Laguna Xochimilco 300-1 y calle Toluca', 'Xochicalli', '21353', '(colonia Xochicali)', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm', NULL, NULL),
('4', 'Puerto Seguro', 'Mexicali', 'Baja California', 'Ferrol # 221', 'Villa Lomas Altas 2da. Sección', '21355', 'Fracc. Villa Lomas Altas 2da. Sección', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm (verano) 7:00 a 8:30 pm (invierno)', NULL, NULL),
('4', 'Un día a la vez', 'Mexicali', 'Baja California', 'Av. Laguna Mayrán #1000 y Reyna Isabel la Católica', 'Villa del Rey Primera Etapa', '21354', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm (verano) y de 7:00 a 8:30 pm (invierno)', NULL, NULL),
('4', 'Unidad', 'Mexicali', 'Baja California', 'Boulevard Anáhuac #1398-9 (Plaza Magna)', 'Casa Magna', '21354', 'Plaza Magna', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm', NULL, NULL),
('4', 'Vivir mejor "El rescate"', 'Mexicali', 'Baja California', 'Calle Gilas #2368 esquina con Gran Canaria', 'Hacienda de Castilla', '21327', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:30 a 9:00 pm y domingo de 11:00 am. a 12:30 pm.', NULL, NULL),
('4', '12 promesas', 'Mexicali', 'Baja California', 'Cataratas del Niagara #267 Local 7', 'Santa Mónica', '21339', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario 7:30 a 9:00 pm. Sesiones matutinas de lunes a viernes de 8:00 a 9:30 am. Sábado y domingo de 9:00 a 11:00 am.', NULL, NULL),
('4', 'Hidalgo', 'Mexicali', 'Baja California', 'Av. 1810 #2148 y Hacienda de Corralejo', 'Hidalgo', '21389', 'Esquina con Hacienda de Corralejo', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm y domingo de 9:00 a 11:00 am.', NULL, NULL),
('4', 'Primero de Enero', 'Mexicali', 'Baja California', 'Av. Jerez #699', 'Ejido Zacatecas', '21090', 'Esq. Moyahua', 'Tradicional', 'Mixto', 'Español', 'Diario de 12:00 a 1:30 pm y de 8:00 a 9:30 pm.', NULL, NULL),
('4', 'Transmítelo', 'Mexicali', 'Baja California', 'Av. Granada y calle Murcia #1500', 'Conjunto Urbano Esperanza', '21350', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 7:30 a 9:30 pm y domingo de 10:00 a 11:30 am', NULL, NULL),
('4', 'Una nueva vida', 'Mexicali', 'Baja California', 'Av. Lombardo Toledano #1200 E', 'Hacienda del Bosque', '21355', 'Av. Lombardo Toledano #1200-5 cerca de la avenida Manuel Gomez Morin', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm (invierno) y 8:00 a 9:30 pm (verano); domingos de 11:00 am a 12:00 pm, lunes, miércoles y viernes de 9:00 a 10:30 am.', NULL, NULL),
('4', 'Cucapah', 'Mexicali', 'Baja California', 'Blvd.Benito Juarez #3739 segundo piso', 'Residencias Imperiales', '21285', '(Fraccionamiento Residencias) Frente al Bar la Tetera', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm y (horario vespertino) y de lunes a viernes de 8:00 a 9:30 am (horario matutino).', NULL, NULL),
('4', 'Andando sobrio', 'Mexicali', 'Baja California', 'Calle Franciso Javier del Castillo 742, Solidaridad Social', 'Solidaridad Social', '21387', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm (verano) y 6:00 a 7:30 pm (invierno)', NULL, NULL),
('5', 'South Campos Serenity Group', 'San Felipe', 'Baja California', 'Km. 35.5 federal highway 5, B.C.', 'Ejido Delicias', '21854', 'South Campos Community Center', 'Tradicional', 'Mixto', 'Inglés', 'Jueves 9:30 a 10:30 am. (En verano el grupo cierra temporalmente y se asiste a las junta de los grupos de san Felipe, B.C.)', NULL, NULL),
('5', 'Internacional', 'San Felipe', 'Baja California', 'Av. Mar del Caribe Sur #1010-B, Carretera a Puertecitos', 'Nuevo San Felipe', '21850', 'Serenity Hall', 'Tradicional', 'Mixto', 'Inglés', 'Lunes 9:30 a 10:30 am, miércoles 5:00 a 6:00 pm. Sábado 5:00 a 6:00 pm y domingo (hombres) 5:00 a 6:00 pm.', NULL, NULL),
('5', 'San Felipe', 'San Felipe', 'Baja California', 'Av. Mar de las Flores #221', 'Segunda Sección', '21850', 'Una cuadra antes de la glorieta', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm y el domingo reunión matutina de 10:00 a 11:30 am.', NULL, NULL),
('5', 'Living Sober', 'San Felipe', 'Baja California', 'Campo Ocotillo, Carretera San Felipe-Mexicali C.P. 21850 Kilómetro 182, Ejido Plan Nacional, San Felipe B.C. “Club Live and Let Live”', 'Plan Nacional Agrario', '21850', '“Club Live and Let Live”', 'Tradicional', 'Mixto', 'Inglés', 'Viernes a las 6:00 a 7:00 pm', NULL, NULL),
('5', '17 de Octubre', 'San Felipe', 'Baja California', 'kM.122 Poste #1 calle Mar Irlanda Zona del Arroyo', 'Segunda Sección', '21850', 'entre calle Veracruz e Isla Silicia', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm', NULL, NULL),
('5', 'Renacer', 'San Felipe', 'Baja California', 'Campo Ocotillo Km. 182 Carretera Mexicali-San Felipe (ubicación temporal Club de Pesca #254 calle 7 y toronja)', 'Club de Pesca', '21850', '(ubicación temporal Club de Pesca #254 calle 7 y toronja)', 'Tradicional', 'Mixto', 'Español', 'Jueves, viernes y sábado de 12:00 a 1:00 pm', NULL, NULL),
('6', '21 de julio', 'Mexicali', 'Baja California', 'Acatita de Bajan #1198, esq. Rio Quelite', 'Independencia', '21290', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm (invierno) y 8:00 a 9:30 pm (verano)', NULL, NULL),
('6', 'Fortaleza', 'Mexicali', 'Baja California', 'Blvd. Carranza #2001-4 y Rio Mizantla', 'Paseos del Sol', '21399', 'Arriba de la papeleria "Calafia"', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm.', NULL, NULL),
('6', 'Hoy es diferente', 'Mexicali', 'Baja California', 'Av. Manzanilla #623 entre calle Olivo y Heliotropo', 'El Ciprés', '21384', NULL, 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 7:00 a 8:30 pm. (invierno) y de 8:00 a 9:30 pm. (verano)', NULL, NULL),
('6', 'Libertad', 'Mexicali', 'Baja California', 'Laguna Zempoala #2100 esq. Rio Concepción', 'Paseos del Sol', '21399', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm. (invierno) y de 8:00 a 9:30 pm. (verano). Matutinas: miércoles y domingo de 10:00 am a 12:00 pm.', NULL, NULL),
('6', 'Una visión para ti', 'Mexicali', 'Baja California', 'Calzada Rosa del Desierto #4272 esquina con Avenida Fragaria, fraccionamiento Monarcas', 'Monarcas Residencial', '21395', '(a 200 metros de carretera a San Luis)', 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm.', NULL, NULL),
('6', 'Bill y Bob', 'Mexicali', 'Baja California', 'Ignacio Zaragoza y calle 4ta.', 'Puebla (Ejido Puebla)', '21395', NULL, 'Tradicional', 'Mixto', 'Español', 'Todos los días de 7:30 a 9:00 pm; domingo de 12:00 a 2:00 pm.', NULL, NULL),
('6', 'Experiencia espiritual', 'Mexicali', 'Baja California', 'Av. del Ayuntamiento y calle Roberto Montenegro #1799', 'Sol de Reyes', '21379', 'Atrás de Plaza Carranza', 'Tradicional', 'Mixto', 'Español', 'Diario de 8:30 a 10:00 am y de 8:00 a 9:30 pm.', NULL, NULL),
('6', 'Gratitud', 'Mexicali', 'Baja California', 'Calle 6ta esquina con callejón Hilario Local B, Delegación Palaco', 'González Ortega', '21396', 'Calle Hilario Ruelas y calle Sexta)', 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 8:00 a 9:30 pm. (verano) y 7:00 a 8:30 pm. (invierno)', NULL, NULL),
('6', 'Humildad', 'Mexicali', 'Baja California', 'Onceava y Rio Lacantún (enfrente de avenida San Pedro Mezquital #4352 y calle 11)', 'Villa Verde', '21395', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 8:00 a 9:30 pm.', NULL, NULL),
('6', 'Pedregal', 'Mexicali', 'Baja California', 'Calz. Gustavo Vildosola Castro #4051 L-7 Mexicali (carr. San Luis enfrente de estructuras y perfiles) Plaza los Reyes.', 'Valle del Pedregal', '21395', 'Plaza los Reyes', 'Tradicional', 'Mixto', 'Español', 'Diario 7:30 a 9:00 pm. Domingo de 9:00 a 11:00 am.', NULL, NULL),
('7', 'Firme voluntad', 'Mexicali', 'Baja California', 'Carretera Estatal #2, Plaza "El General", local 7, Ejido Michoacán de Ocampo.', 'Michoacán de Ocampo', '21700', 'Carretera Estatal #2, Plaza "El General", local 7, Ejido Michoacán de Ocampo.', 'Tradicional', 'Mixto', 'Español', 'Diario 6:00 a 7:30 pm. (invierno) y 7:00 a 8:30 pm. (verano)', NULL, NULL),
('7', 'Alto', 'Mexicali', 'Baja California', 'Calle del Angel y avenida Cupula #598', 'Misión del Ángel', '21387', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm. Domingo matutina 8:00 a 9:30 am.', NULL, NULL),
('7', 'Oaxaca', 'Mexicali', 'Baja California', 'Lázaro Cadenas #123-3', 'Delta (Estación Delta) Ejido Oaxaca', '21700', 'Ejido Oaxaca', 'Tradicional', 'Mixto', 'Español', 'Lunes a viernes de 6:00 a 7:30 pm. (invierno) y de 7:00 a 8:30 pm. (verano)', NULL, NULL),
('7', 'Cambio de conciencia', 'Mexicali', 'Baja California', 'KM.11.5 Carretera a San Felipe Rancho Roa', '4 Cerro Prieto (Rancho el Roa)', '21703', 'A un costado del jardin Rancho Roa', 'Tradicional', 'Mixto', 'Español', 'Lunes a sábado de 6:00 a 7:30 pm; domingo de 11:00 am. a 12:30 pm.', NULL, NULL),
('7', 'Una nueva visión', 'Mexicali', 'Baja California', 'Vicente Guerrero #501 y 9na. Ejido Gpe. Victoria km. 43', 'Guadalupe Victoria', '21720', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario 7:00 a 8:30 pm.', NULL, NULL),
('7', '2 de abril', 'Mexicali', 'Baja California', 'Calle 2 de Abril #669 y Poder Judicial', 'Carbajal', '21370', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm. Y de lunes a viernes de 10:00 a 11:30 am.', NULL, NULL),
('7', 'Una esperanza de fe', 'Mexicali', 'Baja California', 'Santiago Xicoténcatl #398, esquina con 13 de septiembre', 'Solidaridad Social', '21387', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:30 a 9:00 pm.', NULL, NULL),
('7', 'Anahuac', 'Mexicali', 'Baja California', 'Av. Michoacán #1427', 'Pueblo Nuevo', '21120', NULL, 'Tradicional', 'Mixto', 'Español', 'Diario de 7:00 a 8:30 pm.', NULL, NULL);
